language: python
branches:
    only:
        - master
        - dogfood
services:
  - postgres
python:
  - "2.7"
env:
  - DB=sqlite
  - DB=postgres
before_install:
  # Having this in the output can make debugging easier:
  - sh -c "if [ $DB = postgres ]; then psql --version; fi"
install:
  - sh -c "if [ $DB = postgres ]; then pip install psycopg2; fi"
  - python setup.py install
before_script:
  - sh -c "if [ $DB = postgres ]; then psql -c 'CREATE DATABASE haas_travis;' -U postgres; fi"
  - sh -c "if [ $DB = postgres ]; then cp ci/testsuite.cfg.postgres testsuite.cfg; fi"
script: |
    # On SQLite we run the tests in parallel. This speeds things up
    # substantially, but is currently only safe for sqlite, since it
    # uses an in memory (and  therefore per-process) database.

    # Temporarily disaled till we figure out how to solve https://github.com/CCI-MOC/haas/issues/577
    #    if [ $DB = sqlite ]; then
    #  extra_flags='-n auto'
    #  fi
    py.test $extra_flags tests/unit tests/stress.py
