language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

sudo: required
dist: trusty

cache:
  - pip

addons:
  postgresql: "9.3"
  apt:
    packages:
      - apache2
      - libapache2-mod-wsgi

branches:
  only:
    - master
    - dogfood
    - acl_test
env:
  - DB=sqlite
  - DB=postgres

install:
  - sh -e ci/install.sh

script:
  - sh -e ci/run_unit_tests.sh
  - sh -e ci/run_integration_tests.sh
