"""network ACL

Revision ID: f4a1f5d7ec43
Revises: 6a8c19565060
Create Date: 2016-04-26 13:34:54.910541

"""

# revision identifiers, used by Alembic.
revision = 'f4a1f5d7ec43'
down_revision = '6a8c19565060'
branch_labels = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_projects',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )
    op.alter_column(u'network', 'owner_id', new_column_name='creator_id')
    op.drop_column(u'network', 'access_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'network', sa.Column('access_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column(u'network', 'owner_id', new_column_name='creator_id')
    op.drop_constraint(None, 'network', type_='foreignkey')
    op.create_foreign_key(u'network_access_id_fkey', 'network', 'project', ['access_id'], ['id'])
    op.drop_table('network_projects')
    ### end Alembic commands ###
